FROM python:3.8-slim
RUN apt update \
&& apt install build-essential zlib1g-dev libjpeg-dev libopenjp2-7-dev -y \
&& pip install --no-cache-dir fastapi uvicorn python-multipart Pillow \
&& apt purge build-essential -y \
&& rm -rf /var/lib/apt/lists/*

#COPY ./app /app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
